### ISSUE TITLE
Can it support the s3dis dataset?

### ISSUE THREAD

**Issue by Lizhinwafu** [Pointcept/SegmentAnything3D#1]

**Comment by yhyang-myron** [comment]
At present, we only have a version of the ScanNet dataset, which may be applied to other datasets in the future！

**Comment by Gofinge** [comment]
Hi, S3DIS does have 2D data. Please further refer [here](http://buildingparser.stanford.edu/dataset.html). In Pointcept, we also try to render normal vectors of S3DIS points from the raw data source.
