### ISSUE TITLE
Question about pcd_ensemble

### ISSUE THREAD

**Issue by Lszcoding** [Pointcept/SegmentAnything3D#10]
Hi,
Thanks for your SAM3D. I have a question about "org_path" in sam3d.py/pcd_ensemble. Could you please explain what the "org_path" parameter in this function refers to？

Thank you

**Comment by yhyang-myron** [comment]
Hi, thanks for your interests!

**Comment by yhyang-myron** [comment]
Hi, thanks for your interests!
"org_path" is the path of the segmentation result generated by SAM3D.
"new_path" is the path of the segmentation result you want to use to do ensemble option with the SAM3D result.

**Comment by yhyang-myron** [comment]
Hi, thanks for your interests!
"new_path" is the path of the segmentation result generated by SAM3D.
"org_path" is the path of the segmentation result you want to use to do ensemble option with the SAM3D result.
For here, "org_path" is the path of a json file obtained from [here](https://github.com/ScanNet/ScanNet/tree/master/Segmentator).
