### ISSUE TITLE
Why does "sam3d.py" run as a ".pth" file?

### ISSUE THREAD

**Issue by LinLin1031** [Pointcept/SegmentAnything3D#12]
Why does "sam3d.py" run as a ".pth" file? Normally, shouldn't the result of semantic segmentation be a tag file or a point cloud file?

".pth" file is the final training result? If so, how should I test it?

**Comment by LinLin1031** [comment]
@yhyang-myron @Gofinge 
Hope to hear from you soon, thanks!

**Comment by ayaan-mphasis** [comment]
Hi, I have the same doubt. Could you please clarify. And how can I possible visualise its results

**Comment by yhyang-myron** [comment]
Hi. The group_id generated by sam3d.py is in the .pth file. And you visualize it with [here](https://github.com/Pointcept/SegmentAnything3D/blob/75311878df2aba980a85e7d25507ccf4dd155d65/util.py#L246C1-L246C1).

**Comment by ayaan-mphasis** [comment]
@yhyang-myron The .pth file that is being generated as the output for me is a simple array with shape (81369,)
Is there supposed to be a key names as group_id in the output? I want to interpret the output .pth file better.

**Comment by yhyang-myron** [comment]
The array in the final .pth file is the group_id for every point in the original point clouds, and you can use it with original coordinates and color.

**Comment by BKINGING** [comment]
Hello, how can I solve this problem?
Traceback (most recent call last):
File "sam3d.py", line 283, in
voxelize, args.th, train_scenes, val_scenes, args.save_2dmask_path)
File "sam3d.py", line 239, in seg_pcd
indices, dis = pointops.knn_query(1, gen_coord, offset, scene_coord, new_offset)
AttributeError: module 'pointops' has no attribute 'knn_query'
