### ISSUE TITLE
Is this method work on outdoor Scenes?

### ISSUE THREAD

**Issue by YinengXiong** [Pointcept/SegmentAnything3D#13]
Is this method work on outdoor Scenes? like KITTI or NuScenes dataset

**Comment by yhyang-myron** [comment]
Sorry for not replying in a timely manner. We have not yet attempted on the outdoor point cloud.

**Comment by YinengXiong** [comment]
> Sorry for not replying in a timely manner. We have not yet attempted on the outdoor point cloud.

In your opinion, ss the proposed method only work on static scenes?

**Comment by yhyang-myron** [comment]
To my view, the method can also work on other 3D scenes with RGBD data. Specifically, you can follow [here](https://github.com/Pointcept/SegmentAnything3D/issues/9#issuecomment-1563056683).
