### ISSUE TITLE
could someone please provide mini sample datasets?

### ISSUE THREAD

**Issue by flydragon2018** [Pointcept/SegmentAnything3D#14]
The actual datasets too big to download and run for  learning purpose.

Thanks in advance!

**Comment by yhyang-myron** [comment]
Thanks for your interest in our work！
You can specify to only download specific scenes of ScanNet.

**Comment by trinhtuanvubk** [comment]
Hi, I cant find anyway to download a mini sample data. Can anyone help me. I just want to use to debug this code to understand, then use with my own dataset
