### ISSUE TITLE
The run results did not meet expectations.

### ISSUE THREAD

**Issue by LinLin1031** [Pointcept/SegmentAnything3D#17]
Why do I get different results when I follow the tutorial step by step to configure the environment and run the code? 

As shown below, there are a lot of super pixels that are not merged together.

I have tried to reconfigure the environment and run the unmodified source code, but it still fails.

![image](https://github.com/Pointcept/SegmentAnything3D/assets/50825626/bb60be6d-ec64-475b-bfbb-7baa40fb8f62)

![image](https://github.com/Pointcept/SegmentAnything3D/assets/50825626/d2466cba-9f32-4d01-8ea8-14ea772bb244)

![image](https://github.com/Pointcept/SegmentAnything3D/assets/50825626/7a325438-f413-4693-9a5e-9287cfc3ff47)

**Comment by LinLin1031** [comment]
@yhyang-myron Please ask for advice.

**Comment by yhyang-myron** [comment]
Thanks for your interests!
Maybe first you can check if the 2d results from SAM are reasonable. And check if the dimensions of the 2D image are consistent. Next, you can use a 2D RGBD data reconstruction to ensure that it remains consistent with the original scene.

**Comment by LinLin1031** [comment]
Sorry, I still don't understand what you mean.

I once successfully reproduced the results of the experiment you posted one night. But when I re-ran it the next day, I had the problem mentioned above. And after several attempts (e.g. reconfiguring the virtual environment, re-downloading the source code) I still could not reproduce it successfully. Honestly, it's very crushing and I don't know how to proceed.

**Comment by yhyang-myron** [comment]
It's so strange. I think the problem may arise on the dataset. Have you checked if the data you used is consistent with the first day?

**Comment by BKINGING** [comment]
> Sorry, I still don't understand what you mean.
> 
> I once successfully reproduced the results of the experiment you posted one night. But when I re-ran it the next day, I had the problem mentioned above. And after several attempts (e.g. reconfiguring the virtual environment, re-downloading the source code) I still could not reproduce it successfully. Honestly, it's very crushing and I don't know how to proceed.

**Comment by BKINGING** [comment]
> 对不起，我仍然不明白你的意思。
> 
> 我曾经成功地复制了你一天晚上发布的实验结果。但是当我第二天重新运行它时，我遇到了上面提到的问题。经过几次尝试（例如重新配置虚拟环境，重新下载源代码），我仍然无法成功重现它。老实说，这非常令人沮丧，我不知道如何进行。



> Why do I get different results when I follow the tutorial step by step to configure the environment and run the code?
> 
> As shown below, there are a lot of super pixels that are not merged together.
> 
> I have tried to reconfigure the environment and run the unmodified source code, but it still fails.
> 
> ![image](https://user-images.githubusercontent.com/50825626/251675676-bb60be6d-ec64-475b-bfbb-7baa40fb8f62.png)
> 
> ![image](https://user-images.githubusercontent.com/50825626/251675957-d2466cba-9f32-4d01-8ea8-14ea772bb244.png)
> 
> ![image](https://user-images.githubusercontent.com/50825626/251676236-7a325438-f413-4693-9a5e-9287cfc3ff47.png)

Excuse me, when you run the code, the result is a series of pth files? How do I get a visualization?
