### ISSUE TITLE
missing intrinsics.txt file

### ISSUE THREAD

**Issue by IKAROS66** [Pointcept/SegmentAnything3D#18]
When I preprocess the RGBD data in the data preprocessing step, I processed it according to the prepare_2d_data.py file, and each scene only generated four folders of color, depth, label, and pose, but when I ran the sam3d.py file, it prompted me that I could not find the intrinsics.txt file under the intrinsics folder.This error is reported on the second line of the get_pcd function in the sam3d.py file, how can I generate intrinsics.txt data for each scene？

![4cfedb57068d6a3f2de15d59160c6975](https://github.com/Pointcept/SegmentAnything3D/assets/86828000/ab28c8d2-ef41-4bba-a83d-1227ae9a61a1)

**Comment by LinLin1031** [comment]
This project code has the function to generate this file, you just need call it after you find it.
