### ISSUE TITLE
Optimal parameter values

### ISSUE THREAD

**Issue by LinLin1031** [Pointcept/SegmentAnything3D#19]
I would like to ask you, in the fourth step of Pipeline, in the command ". /segmentator input.ply [kThresh=0.01] [segMinVerts=20]", what is the optimal value to set for the parameters "kThresh" and "segMinVerts"?

**Comment by yhyang-myron** [comment]
Hi, you can follow [here](https://github.com/ScanNet/ScanNet/tree/master/Segmentator) for more details.

**Comment by yhyang-myron** [comment]
I directly use the default parameters ([kThresh=0.01] [segMinVerts=20]).

**Comment by LinLin1031** [comment]
May I ask what command you entered ". /segmentator input.ply [kThresh=0.01] [segMinVerts=20]" or ". /segmentator input.ply 0.01 20", because I found that for the command ". /segmentator input.ply [kThresh=0.01] [segMinVerts=20]", the real values of kThresh and segMinVerts are not 0.01 and 20 as set.

**Comment by yhyang-myron** [comment]
I use this ". /segmentator input.ply 0.01 20"

**Comment by BKINGING** [comment]
Excuse me, scannetv2 dataset is too large, do we need to download it all? Or just download these four?
python 1.py -o scannet/ --type _vh_clean_2.ply
python 1.py -o scannet/ --type _vh_clean_2.labels.ply
python 1.py -o scannet/ --type _vh_clean_2.0.010000.segs.json
python 1.py -o scannet/ --type .aggregation.json

**Comment by BKINGING** [comment]
Excuse me,Do you have any questions about this step? Could you take a look for me? Is it the dataset? I only got fourpython 1.py -o scannet/ --type _vh_clean_2.ply
python 1.py -o scannet/ --type _vh_clean_2.labels.ply
python 1.py -o scannet/ --type _vh_clean_2.0.010000.segs.json
python 1.py -o scannet/ --type .aggregation.json.

python scannet-preprocess/prepare_2d_data/prepare_2d_data.py --scannet_path dataout/train --output_path data/scannetv2_images --export_la
bel_images
Namespace(export_label_images=True, frame_skip=20, label_map_file='D:\Desktop\dianyun\SegmentAnything3D-main\data\scannetv2\scannetv2-labels.combined.tsv', label_type='label-filt
', output_image_height=240, output_image_width=320, output_path='data/scannetv2_images', scannet_path='dataout/train')
Traceback (most recent call last):
File "scannet-preprocess/prepare_2d_data/prepare_2d_data.py", line 118, in
main()
File "scannet-preprocess/prepare_2d_data/prepare_2d_data.py", line 71, in main
label_map = util.read_label_mapping(opt.label_map_file, label_from='id', label_to='nyu40id')
File "D:\Desktop\dianyun\SegmentAnything3D-main\scannet-preprocess\prepare_2d_data\util.py", line 42, in read_label_mapping
if represents_int(mapping.keys()[0]):
TypeError: 'dict_keys' object is not subscriptable

**Comment by LinLin1031** [comment]
> I use this ". /segmentator input.ply 0.01 20"

Hi, I also used the parameter values of 0.01 and 20, but the visualization after ensembling is shown in the figure. The walls in it do not show up as a uniform color, which does not seem to be the expected result. May I ask what should be done to solve this?

![image](https://github.com/Pointcept/SegmentAnything3D/assets/50825626/cc591a74-f63c-4c95-a739-1ac57e9939fe)

**Comment by LinLin1031** [comment]
I see, my problem was in the final step of visualization using the **pcd_ensemble function**.

![image](https://github.com/Pointcept/SegmentAnything3D/assets/50825626/a9f9fe69-b2aa-45f0-916d-a2011fc3673d)

First of all, this image above is from step 4 of your work (Figure 2 from the paper). In it, the results from SAM3D and the over-segmentation results from Segmentor are ensemble to get the final result.

But the ensembled result I get (as shown in the quote below) looks exactly the same as the **over-segmentation result**.

> > I use this ". /segmentator input.ply 0.01 20"
> 
> Hi, I also used the parameter values of 0.01 and 20, but the visualization after ensembling is shown in the figure. The walls in it do not show up as a uniform color, which does not seem to be the expected result. May I ask what should be done to solve this?
> 
> ![image](https://user-images.githubusercontent.com/50825626/255593519-cc591a74-f63c-4c95-a739-1ac57e9939fe.png)

Among the parameter values I set in the call to the pcd_ensemble function are as follows:
```
org_path = r'/media/data/scannetv2/scans/scene0000_00/scene0000_00_vh_clean_2.0.010000.segs.json'
new_path = r'/media/zl/SegmentAnything3D-main/result_pcd/scene0000_00.pth'
data_path = r'/media/zl/SegmentAnything3D-main/data/scannet/train/scene0000_00.pth'
vis_path = r'/media/zl/SegmentAnything3D-main/result_ply/scene0000_00_ensemble.ply'
pcd_ensemble(org_path, new_path, data_path, vis_path)
```
So what exactly is my problem?

**Comment by yhyang-myron** [comment]
Hi, you can find how to set the path from [here](https://github.com/Pointcept/SegmentAnything3D/issues/10#issuecomment-1571454770).

**Comment by Lee123lyl** [comment]
i meet the same problem. Need help!


> I see, my problem was in the final step of visualization using the **pcd_ensemble function**.
> 
> ![image](https://private-user-images.githubusercontent.com/50825626/255785173-a9f9fe69-b2aa-45f0-916d-a2011fc3673d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTA0NzQsIm5iZiI6MTcyMTYxMDE3NCwicGF0aCI6Ii81MDgyNTYyNi8yNTU3ODUxNzMtYTlmOWZlNjktYjJhYS00NWYwLTkxNmQtYTIwMTFmYzM2NzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAxMDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZDg0ZGY2YzVmZTJjMzA3NmE1ZTc4NjIxNGNhYTRlYzg2ODE5Mjc4MjU0YjE4ZTU4MGVlNzUwNzQyMDZkYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b9Fp0nLUze1064XQp7684nVpsyZg_vyrwG4Vq4g6Cy0)
> 
> First of all, this image above is from step 4 of your work (Figure 2 from the paper). In it, the results from SAM3D and the over-segmentation results from Segmentator are ensemble to get the final result.
> 
> But the ensembled result I get (as shown in the quote below) looks exactly the same as the **over-segmentation result**.
> 
> > > I use this ". /segmentator input.ply 0.01 20"
> > 
> > 
> > Hi, I also used the parameter values of 0.01 and 20, but the visualization after ensembling is shown in the figure. The walls in it do not show up as a uniform color, which does not seem to be the expected result. May I ask what should be done to solve this?
> > ![image](https://user-images.githubusercontent.com/50825626/255593519-cc591a74-f63c-4c95-a739-1ac57e9939fe.png)
> 
> Among the parameter values I set in the call to the pcd_ensemble function are as follows:
> 
> ```
> org_path = r'/media/data/scannetv2/scans/scene0000_00/scene0000_00_vh_clean_2.0.010000.segs.json'
> new_path = r'/media/zl/SegmentAnything3D-main/result_pcd/scene0000_00.pth'
> data_path = r'/media/zl/SegmentAnything3D-main/data/scannet/train/scene0000_00.pth'
> vis_path = r'/media/zl/SegmentAnything3D-main/result_ply/scene0000_00_ensemble.ply'
> pcd_ensemble(org_path, new_path, data_path, vis_path)
> ```
> 
> So what exactly is my problem?

**Comment by LinLin1031** [comment]
> i meet the same problem. Need help!

Please elaborate on this issue as a lot of time has passed.

**Comment by Lee123lyl** [comment]
Thank you very much for your reply!
I call to pcd_ensemble function just like you.

org_path = .../scene0000_00_vh_clean_2.0.010000.segs.json'
new_path = .../scene0000_00.pth'
data_path = .../scene0000_00.pth'
vis_path = .../scene0000_00_ensemble.ply'
pcd_ensemble(org_path, new_path, data_path, vis_path)

And the ensembled result I got looks exactly the same as the over-segmentation result.(The picture I uploaded is my result. It is obviously the over-segmentation you mentioned, not sam3d (ensembled)

how can i get the Merge 2 Segmentation Results? 
![Screenshot from 2024-07-19 14-59-39](https://github.com/user-attachments/assets/f3722558-7e79-460d-9cad-e0a3dd1f142d)

**Comment by LinLin1031** [comment]
You can visualise the SAM3D result separately to see if it is the same as in the text. Note: not SAM3D (ensembled).

**Comment by Lee123lyl** [comment]
Its the same. How did you solve the problem you encountered at that time?

**Comment by Lee123lyl** [comment]
Its the same. How did you solve the problem you encountered at that [time?](https://github.com/Pointcept/SegmentAnything3D/issues/19#:~:text=new_path%2C%20data_path%2C%20vis_path)-,So%20what%20exactly%20is%20my%20problem%3F,-Author)

**Comment by Lee123lyl** [comment]
Its the same. How did you solve the problem you encountered at that time?
![2](https://github.com/user-attachments/assets/8bb38e3c-43ab-40a3-b726-690538d18cc4)

**Comment by LinLin1031** [comment]
Sorry, I can't recall. I think you can find the problem by debugging it. I was going to reopen the results of the run at the time, but realised I couldn't find it anymore.
