### ISSUE TITLE
scannetv2

### ISSUE THREAD

**Issue by BKINGING** [Pointcept/SegmentAnything3D#21]
scannetv2 dataset is too large, do we need to download it all? Or just download these four?
python 1.py -o scannet/ --type  _vh_clean_2.ply
python 1.py -o scannet/ --type  _vh_clean_2.labels.ply
python 1.py -o scannet/ --type  _vh_clean_2.0.010000.segs.json
python 1.py -o scannet/ --type  .aggregation.json

**Comment by yhyang-myron** [comment]
Hi, you just need these four for this project. Also, if you want to have a try first, you can just download specific scenes.

**Comment by BKINGING** [comment]
Thank you for your reply

**Comment by BKINGING** [comment]
Hello, how can I solve this problem?
Traceback (most recent call last):
File "sam3d.py", line 283, in
voxelize, args.th, train_scenes, val_scenes, args.save_2dmask_path)
File "sam3d.py", line 239, in seg_pcd
indices, dis = pointops.knn_query(1, gen_coord, offset, scene_coord, new_offset)
AttributeError: module 'pointops' has no attribute 'knn_query'

**Comment by RyanG41** [comment]
Hi, @BKINGING Do we really need only the four? It asked me for the .sens data when I run prepare_2d_data :(
Instead I download the _scannet_frames_25k_ zip file, will it work? Thanks.

**Comment by Cedric-Perauer** [comment]
Just in case someone else comes across this and wants to use it without downloading much data while being a bit with Scannet download :

1.  Download the already preprocessed scenes from [here](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/wuxy_connect_hku_hk/EREuB1If2DNEjz43-rdaVf4B5toMaIViXv8gEbxr9ydeYA?e=ffXeG4) to obtain preprocessed scenes as mentioned in the [Pointcept readme](https://github.com/Pointcept/Pointcept). 

2. To get the image data, use the [scannet download script](https://kaldir.vc.in.tum.de/scannet/download-scannet.py) and download processed test frames : 

```bash
python download_scannnet.py -o <output_dir> --test_frames_2d
```



3. Make slight changes in code : 

- change [this line](https://github.com/Pointcept/SegmentAnything3D/blob/856720ca4927e894a12f3d267c66f93eda595ef6/sam3d.py#L52) to fit the format for intrinsics from test_frames_2d : 
  ```python 
  intrinsic_path = join(rgb_path, scene_name,'intrinsics_depth.txt')
  ```
- add simple else condition [here](https://github.com/Pointcept/SegmentAnything3D/blob/856720ca4927e894a12f3d267c66f93eda595ef6/sam3d.py#L229) to enable run on test data : 
  ```python
  if scene_name in train_scenes:
          scene_path = join(data_path, "train", scene_name + ".pth")
      elif scene_name in val_scenes:
          scene_path = join(data_path, "val", scene_name + ".pth")
      else : 
          scene_path = data_path
  ```
