### ISSUE TITLE
The code ran into a problem

### ISSUE THREAD

**Issue by BKINGING** [Pointcept/SegmentAnything3D#22]
Do you have any questions about this step? Could you take a look for me? Is it the dataset? I only got fourpython 1.py -o scannet/ --type _vh_clean_2.ply
python 1.py -o scannet/ --type _vh_clean_2.labels.ply
python 1.py -o scannet/ --type _vh_clean_2.0.010000.segs.json
python 1.py -o scannet/ --type .aggregation.json.

python scannet-preprocess/prepare_2d_data/prepare_2d_data.py --scannet_path dataout/train --output_path data/scannetv2_images --export_la
bel_images
Namespace(export_label_images=True, frame_skip=20, label_map_file='D:\Desktop\dianyun\SegmentAnything3D-main\data\scannetv2\scannetv2-labels.combined.tsv', label_type='label-filt
', output_image_height=240, output_image_width=320, output_path='data/scannetv2_images', scannet_path='dataout/train')
Traceback (most recent call last):
File "scannet-preprocess/prepare_2d_data/prepare_2d_data.py", line 118, in
main()
File "scannet-preprocess/prepare_2d_data/prepare_2d_data.py", line 71, in main
label_map = util.read_label_mapping(opt.label_map_file, label_from='id', label_to='nyu40id')
File "D:\Desktop\dianyun\SegmentAnything3D-main\scannet-preprocess\prepare_2d_data\util.py", line 42, in read_label_mapping
if represents_int(mapping.keys()[0]):
TypeError: 'dict_keys' object is not subscriptable

**Comment by yhyang-myron** [comment]
Hi, do you have the label_map_file?

**Comment by BKINGING** [comment]
No,How do I download it?

**Comment by yhyang-myron** [comment]
You can download it with the official script. You can get the script from [here](https://github.com/ScanNet/ScanNet).

**Comment by BKINGING** [comment]
Excuse me, can I say this step more clearly? Small white just get started, this step specific how to operate? How exactly is this file generated? How to use it?

**Comment by yhyang-myron** [comment]
You can see the command in the script like _parser.addargument('--Label map action='storetrue' help='download label map file")_. And the file is used at [here](https://github.com/Pointcept/SegmentAnything3D/blob/75311878df2aba980a85e7d25507ccf4dd155d65/scannet-preprocess/prepare_2d_data/prepare_2d_data.py#L40C52-L40C52).

**Comment by BKINGING** [comment]
THANK YOU!

**Comment by BKINGING** [comment]
Hello, how can I solve this problem?
Traceback (most recent call last):
File "sam3d.py", line 283, in
voxelize, args.th, train_scenes, val_scenes, args.save_2dmask_path)
File "sam3d.py", line 239, in seg_pcd
indices, dis = pointops.knn_query(1, gen_coord, offset, scene_coord, new_offset)
AttributeError: module 'pointops' has no attribute 'knn_query'
