### ISSUE TITLE
Help me, please.

### ISSUE THREAD

**Issue by LinLin1031** [Pointcept/SegmentAnything3D#25]
Hi, I have tried many times to reproduce this work but still not achieving the desired result.

Do you have any other contact information that I would like to ask you for further advice. I hope you can check my code.

Thank you very much!

**Comment by LinLin1031** [comment]
Is it convenient for you to answer my questions in your free time? I would be very grateful!
@yhyang-myron

**Comment by yhyang-myron** [comment]
Sorry for the delayed response. Can you add my qq:1240481806?

**Comment by Davidyao99** [comment]
Hi, I am having the same issue. Could you elaborate on how you managed to resolve this? @LinLin1031 @yhyang-myron Thank you so much!!
