### ISSUE TITLE
The script sam3d.py ran into a problem.

### ISSUE THREAD

**Issue by ayaan-mphasis** [Pointcept/SegmentAnything3D#27]
I am getting this error for line 78 in sam3d.py script
color_image = np.reshape(color_image[mask], [-1,3])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 480 but corresponding boolean dimension is 240

**Comment by yhyang-myron** [comment]
Hi. Size of all 2d data in this project should be [640,480]. Could you check whether the size of depth and RGBD data are [640, 480]?

**Comment by BKINGING** [comment]
Hello, how can I solve this problem?
Traceback (most recent call last):
  File "sam3d.py", line 283, in <module>
    voxelize, args.th, train_scenes, val_scenes, args.save_2dmask_path)
  File "sam3d.py", line 239, in seg_pcd
    indices, dis = pointops.knn_query(1, gen_coord, offset, scene_coord, new_offset)
AttributeError: module 'pointops' has no attribute 'knn_query'
