### ISSUE TITLE
Couldn't locate scannetv2 while preparing RGBD data.

### ISSUE THREAD

**Issue by bipsec** [Pointcept/SegmentAnything3D#28]
While preparing PointCloud data 3 different folders are created. but only the train folder got one .pth. Is it ok? Or am I mistaken? Please let me know about the point cloud data format after preparing it.

And RGBD preparation occurs File not found data/scannetv2.

**Comment by yhyang-myron** [comment]
Sorry for delay. For 3D data, there should be files in all three folders (train, val, test).
Did you download the raw scannetv2 data? You should appoint the data path in the script.

**Comment by bipsec** [comment]
There are three folders created while preparing point cloud data. But only the train folder has some files in it. How can I get all files for all of the folders (train, test, val)?

Yes, I downloaded a few scenes and later I figured out the path for RGBD data preparation.

**Comment by yhyang-myron** [comment]
1. The scenes you downloaded may all in the training dataset. So it doesn't matter for lacking files in val and test folders.
2. What problem did you meet when installing pointops?

**Comment by bipsec** [comment]
![pointops](https://github.com/Pointcept/SegmentAnything3D/assets/66509972/c69333c8-853e-4e1b-be21-94ee6946040b)
![setup_issue](https://github.com/Pointcept/SegmentAnything3D/assets/66509972/d7357b52-8bdb-4977-82b7-b9a94267e746)


Could you enlighten me how to solve these issues?

**Comment by yhyang-myron** [comment]
According to the error message, _/usr/local/cuda/bin/nvcc_ cannot be found when building the pointops. Did you use cuda for compilation. If you used cuda for compilation, there may be a mismatch between the environment and the cuda version.
