### ISSUE TITLE
2D image number for segment

### ISSUE THREAD

**Issue by FinnJob** [Pointcept/SegmentAnything3D#31]
Thank you for your excellent work! 
I wonder how many 2D images are required at minimum for segmenting a 3D point cloud? Thanks!

**Comment by yhyang-myron** [comment]
Thank you for your interest in our work!
In ScanNet dataset, we directly use one image every 20 frames in one scene. The number of 2D images for every single scene depends on the total number of frames. We didn't try the relationship between the number of 2D images and segmentation quality.

**Comment by FinnJob** [comment]
Thank you for your reply! 
And one more thing. Is it necessary for each frame of the image to be roughly continuous? Would it be feasible to use discretely captured images from different camera positions?

**Comment by yhyang-myron** [comment]
The images should be as continuous as possible, as we use a bottom-up block merging method. We first merge adjacent images. You may also try to disrupt the order of the results.

**Comment by FinnJob** [comment]
Ok, thanks!
