### ISSUE TITLE
Result Reproduction

### ISSUE THREAD

**Issue by JUNJIE99** [Pointcept/SegmentAnything3D#4]
Hey, thanks for your work.

I reproduce the results in scene0000_00, I follow the default setting in your repo, but I get about 817 instances in an scene, which is seemed not reasonable.

I think maybe there are something wrong when I prepare the dataset. So I want to check that whether the frames_skip is 20 when prepare the rgbd data,  and did your rgbd frames are come from .sens file? Or maybe other issues that I haven't noticed...

Thank you!

**Comment by JUNJIE99** [comment]
I change the frames_skip from 20 to 1, it doesn't seem to work (with 731 instance id in an single scene)

**Comment by yhyang-myron** [comment]
Hi. The 2d dataset settings follow BPNet. But we changed the frame size from [320,240] to [640,480]. Yes, frames_skip is 20 and rgbd frames come from .sens file. Maybe you can check here for more details. [https://github.com/wbhu/BPNet]

**Comment by JUNJIE99** [comment]
> 

Thanks for your reply!
I have tried changed the frame size from [320,240] to [640,480], but it occurs an error:
`boolean index did not match indexed array along dimension 0; dimension is 480 but corresponding boolean dimension is 240`  in [https://github.com/Pointcept/SegmentAnything3D/blob/75311878df2aba980a85e7d25507ccf4dd155d65/sam3d.py#L76]
After obtaining the group IDs, should I add a code simply resize the color image back to [320,240]?

Thank you!

**Comment by yhyang-myron** [comment]
Sorry for not expressing myself clearly. We changed the size for everything in 2d from [320, 240] to [640, 480] during generating 2D data, including color, depth...

**Comment by JUNJIE99** [comment]
> Sorry for not expressing myself clearly. We changed the size of everything in 2d from [320, 240] to [640, 480] during generating 2D data, including color, depth... So you don't need to resize the color image.

Thanks for your quick reply.
However, in [sam.py](https://github.com/Pointcept/SegmentAnything3D/blob/75311878df2aba980a85e7d25507ccf4dd155d65/sam3d.py),it seems like the size of the depth image is not being converted. There might be some mistakes?

**Comment by JUNJIE99** [comment]
> Sorry for not expressing myself clearly. We changed the size of everything in 2d from [320, 240] to [640, 480] during generating 2D data, including color, depth... So you don't need to resize the color image.

Thanks for your quick reply.
I will regenerate the 2D data to [640, 480] and try again.

Thank you!

**Comment by JUNJIE99** [comment]
Sorry, I would like to confirm one thing again. If I only run [sam3d.py](https://github.com/Pointcept/SegmentAnything3D/blob/75311878df2aba980a85e7d25507ccf4dd155d65/sam3d.py), will I only get the SAM3d results without performing the merge operation(Merge 2 Segmentation Results). In other words, the current results from sam3d.py are the results of the third step in the pipeline.
Thank you!

**Comment by yhyang-myron** [comment]
Yes!

**Comment by JUNJIE99** [comment]
Thank you!

**Comment by LinLin1031** [comment]
> Sorry for not expressing myself clearly. We changed the size of everything in 2d from [320, 240] to [640, 480] during generating 2D data, including color, depth... So you don't need to resize the color image.

https://github.com/Pointcept/SegmentAnything3D/blob/805a1959fe134a76b7e319d59816bacf62603575/scannet-preprocess/prepare_2d_data/prepare_2d_data.py#L42
https://github.com/Pointcept/SegmentAnything3D/blob/805a1959fe134a76b7e319d59816bacf62603575/scannet-preprocess/prepare_2d_data/prepare_2d_data.py#L43

It's not as you say: the image size is not changed when generating the 2D data.

**Comment by BKINGING** [comment]
> 对不起，我想再次确认一件事。如果我只运行 [sam3d.py](https://github.com/Pointcept/SegmentAnything3D/blob/75311878df2aba980a85e7d25507ccf4dd155d65/sam3d.py)，我是否只会获得SAM3d结果而不执行合并操作（合并2分割结果）。换句话说，sam3d.py 的当前结果是管道中第三步的结果。 谢谢！



> Sorry, I would like to confirm one thing again. If I only run [sam3d.py](https://github.com/Pointcept/SegmentAnything3D/blob/75311878df2aba980a85e7d25507ccf4dd155d65/sam3d.py), will I only get the SAM3d results without performing the merge operation(Merge 2 Segmentation Results). In other words, the current results from sam3d.py are the results of the third step in the pipeline. Thank you!

Hello, how do I get the fourth step in the pipeline results

**Comment by JUNJIE99** [comment]
> > 对不起，我想再次确认一件事。如果我只运行 [sam3d.py](https://github.com/Pointcept/SegmentAnything3D/blob/75311878df2aba980a85e7d25507ccf4dd155d65/sam3d.py)，我是否只会获得SAM3d结果而不执行合并操作（合并2分割结果）。换句话说，sam3d.py 的当前结果是管道中第三步的结果。 谢谢！
> 
> > Sorry, I would like to confirm one thing again. If I only run [sam3d.py](https://github.com/Pointcept/SegmentAnything3D/blob/75311878df2aba980a85e7d25507ccf4dd155d65/sam3d.py), will I only get the SAM3d results without performing the merge operation(Merge 2 Segmentation Results). In other words, the current results from sam3d.py are the results of the third step in the pipeline. Thank you!
> 
> Hello, how do I get the fourth step in the pipeline results

@BKINGING You need first generate another segments results by using "Felzenswalb and Huttenlocher's Graph Based Image Segmentation algorithm", which can be found in ScanNet Dataset original repo. Then run merging code in sam3d.py/pcd_ensemble to merge the two results.
