### ISSUE TITLE
How to determine which color belongs to which class？

### ISSUE THREAD

**Issue by xuxiaoxxxx** [Pointcept/SegmentAnything3D#5]
Thanks for your excellent works!
I can get the point cloud with different colors in the end. How can I determine which color belongs to which class？

**Comment by yhyang-myron** [comment]
Hi! The color does not represent the semantic meaning, only represents the group. So we randomly selected the color.

**Comment by ayaan-mphasis** [comment]
Hey @xuxiaoxxxx did you try anything to get the semantic meaning?
