### ISSUE TITLE
The purpose of step "4. Merge 2 Segmentation Results"? 

### ISSUE THREAD

**Issue by garrisonz** [Pointcept/SegmentAnything3D#54]
Hi, thanks for your great work again!

As my understanding, pcd_ensemble is used to merge the segmentation result from SAM3D with the segmentation result from Mesh segmentator. For example, considering the `scene0000_00` scene, after process  "4. Merge 2 Segmentation Results", it is expected to merge two segmentation result into one segmentation result for `scene0000_00`.

What is more, I also find that `scene0000_00`, `scene0000_01` and `scene0000_02` representing the same 3D space. 
My question is:
"4. Merge 2 Segmentation Results" would like to merge the segmentation of `scene0000_00`, `scene0000_01` and `scene0000_02` into single one for `scene 0000`? Or it keeps the three segmentation results sperately for `scene0000_00`, `scene0000_01` and `scene0000_02`?

**Comment by yhyang-myron** [comment]
Hi, Thanks for your interest in our work!
It keeps the three segmentation results separately for scene0000_00, scene0000_01 and scene0000_02.
