### ISSUE TITLE
Inputs required

### ISSUE THREAD

**Issue by antoinemacia** [Pointcept/SegmentAnything3D#6]
Hey! First thank you for exposing your work :) 

Sorry I'm a little confused by what is required to run the script once prepared
- Does the RGB_PATH points to a single image that will be segmented?
- What does the DATA_PATH must point to? An original .ply file as per the examples?

Thank you

**Comment by yhyang-myron** [comment]
Hi! We follow BPNet to get the RGBD data and follow Pointcept to get the pointclouds data in the form of .ply. So the RGB_PATH is the root path to the RGBD data, and the DATA_PATH is the root path to the pointclouds data.
