### ISSUE TITLE
RGBD Cameras

### ISSUE THREAD

**Issue by mohsen-azimi** [Pointcept/SegmentAnything3D#9]
Hi, 
Thanks for developing SAM3D. I have a L515 LiDAR that generates both RGB and Depth frames, or point clouds.  How can I use your codes to prepare my own input dataset? I saw a link in the ReadMe, but it is not clear for me. Could you please clarify a little more? 

Thank you

**Comment by yhyang-myron** [comment]
Hi, Thank you for your interest in our work！
For your own data, first you should check the data format is consistent with ours (point clouds, RGB, intrinsic_depth, intrinsic, pose) and modify [here](https://github.com/Pointcept/SegmentAnything3D/blob/ca97aae3dc6e77d4b3c7b0227a02bf34664f1af3/sam3d.py#L51).
Also, you may modify search_voxel_size and K in [here](https://github.com/Pointcept/SegmentAnything3D/blob/ca97aae3dc6e77d4b3c7b0227a02bf34664f1af3/util.py#L195) to define the maximum distance of the corresponding point.
Finally, you may modify the voxel_size, th and img_size to match your dataset. 
Hope it can be helpful to you!
